### ISSUE TITLE
unable to resolve 'data.okf.fi' (moved under rOpenGov)

### ISSUE THREAD

**Issue by pe3** [louhos/sorvi#13]
Followed the instructions on [sorvi_tutorial.md](https://github.com/rOpenGov/sorvi/blob/master/vignettes/sorvi_tutorial.md#installation):

```
translations <- load_sorvi_data("translations")
print(head(translations))
```
Got an error:
```
> translations <- load_sorvi_data("translations")
Loading http://data.okf.fi/ropengov/avoindata//louhos/translations.rda
Error in load(url(filepath)) : cannot open the connection
In addition: Warning message:
In load(url(filepath)) : unable to resolve 'data.okf.fi'
```
Where is the code for producing `translations.rda`?

**Comment by pe3** [comment]
I would be interested to research if we could move Sorvi towards more reliable dependencies like Wikidata?

**Comment by pe3** [comment]
Uh. This is obviously an abandoned repository. I'm moving the issue forward to rOpenGov

**Comment by antagomir** [comment]
Thanks. For clarity perhaps we should remove the repo. It has been abandoned already for a long time.
